parameters:
  locale: 'uk'

pix_sortable_behavior:
    position_field:
        default: position
        entities:
            App\Entity\Employee: orderPosition

services:
    sonata.admin.employee:
        class: App\Admin\EmployeeAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "Employees" }
        arguments:
           - ~
           - App\Entity\Employee
           - 'PixSortableBehaviorBundle:SortableAdmin'
           - ~
        calls:
           - [ setTranslationDomain, [messages]]

    sonata.admin.role:
        class: App\Admin\RoleAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "Hidden", label: "Roles" }
        arguments:
           - ~
           - App\Entity\Role
           - ~
        calls:
           - [ setTranslationDomain, [messages]]

    sonata.admin.performance:
        class: App\Admin\PerformanceAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "Performances" }
        arguments:
           - ~
           - App\Entity\Performance
           - ~
        calls:
           - [ setTranslationDomain, [messages]]

    admin.repertoire_season:
      class: App\Admin\RepertoireSeasonAdmin
      arguments: [~, App\Entity\RepertoireSeason, ~]
      tags:
        - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: RepertoireSeason }
      public: true

    sonata.admin.performanceEvent:
        class: App\Admin\PerformanceEventAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "PerformanceEvents" }
        arguments:
           - ~
           - App\Entity\PerformanceEvent
           - ~
        calls:
           - [ setTranslationDomain, [messages]]

    sonata.admin.post:
        class: App\Admin\PostAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "Posts" }
        arguments:
           - ~
           - App\Entity\Post
           - ~
        calls:
        - [ setTranslationDomain, [messages]]
        - [ setParameters, ['uk', ['uk', 'en']]]

    sonata.admin.tag:
        class: App\Admin\TagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "Tags" }
        arguments:
            - ~
            - App\Entity\Tag
            - ~
        calls:
        - [ setTranslationDomain, [messages]]

    sonata.admin.employee_group:
        class: App\Admin\EmployeeGroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "Employee Group" }
        arguments:
            - ~
            - App\Entity\EmployeeGroup
            - 'PixSortableBehaviorBundle:SortableAdmin'
        calls:
        - [ setTranslationDomain, [messages]]

    sonata.admin.history:
        class: App\Admin\HistoryAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "History" }
        arguments:
           - ~
           - App\Entity\History
           - ~
        calls:
        - [ setTranslationDomain, [messages]]
