imports:
    - { resource: parameters.yml }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

#fos_rest:
#    param_fetcher_listener: true
#    body_listener: true
#    format_listener: true
#    routing_loader:
#        default_format: json
#    view:
#        view_response_listener: 'force'
#        formats:
#            json: true
#            xml: true
#            yml: false
#            html: false

sensio_framework_extra:
    view:    { annotations: true }
    request:
        converters: true
        auto_convert: false

nelmio_cors:
    paths:
        '^/':
            allow_origin: "%nelmio_cors.origin%"
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            expose_headers: ['*']
            origin_regex: false
            max_age: 3600

#domain_routing:
#    include_routes:
#        "%api_domain%": ['config/routing_api.yml']
#        "%admin_domain%": ['config/routing_sonata_admin.yml']

#doctrine_migrations:
#    dir_name: "%kernel.root_dir%/DoctrineMigrations"
#    namespace: Application\Migrations
#    table_name: migration_versions
#    name: Application Migrations
