doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'

        types:
            AudienceEnum: App\Enum\AudienceEnum

    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    numeric_functions:
                        rand: DoctrineExtensions\Query\Mysql\Rand
                second_level_cache:
                    enabled: true
                metadata_cache_driver:
                    type: pool
                    pool: doctrine.meta_cache_pool
                query_cache_driver:
                    type: pool
                    pool: doctrine.query_cache_pool
                result_cache_driver:
                    type: pool
                    pool: doctrine.result_cache_pool
                naming_strategy: doctrine.orm.naming_strategy.default
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
#                    ApplicationSonataMediaBundle: ~
                    SonataMediaBundle: ~
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity/MappedSuperclass"
                        alias: GedmoTranslatable
                        is_bundle: false
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.array
            doctrine.query_cache_pool:
                adapter: cache.adapter.array
            doctrine.meta_cache_pool:
                adapter: cache.adapter.array
