nelmio_cors:
    defaults:
        allow_origin: "%nelmio_cors.origin%"
        allow_headers: ['*']
        allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
        expose_headers: ['*']
        origin_regex: false
        max_age: 3600
    paths:
        '^/': null
