# See the configuration reference at https://github.com/scheb/two-factor-bundle/blob/master/Resources/doc/configuration.md
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Guard\Token\PostAuthenticationGuardToken

    email:
        digits: 6
        enabled: true
        sender_email: '%env(SENDER_EMAIL_2FA)%'
        sender_name: '%env(SENDER_NAME_2FA)%'
