# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
     sonata.media.admin.gallery_has_media.class: App\Admin\GalleryHasMediaAdmin

services:
    app.twig_extension:
        class: App\Twig\AppExtension
        public: false
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }

    two_performance_events_per_day_validator:
        class: App\Validator\TwoPerformanceEventsPerDayValidator
        arguments: ["@=service('doctrine.orm.default_entity_manager').getRepository('App:PerformanceEvent')", "@translator"]
        tags:
            - { name: validator.constraint_validator, alias: two_performance_events_per_day }

    min_size_slider_image_validator:
        class: App\Validator\MinSizeSliderImageValidator
        arguments: ["@translator"]
        tags:
            - { name: validator.constraint_validator, alias: min_size_slider_image }

    gedmo.listener.sortable:
        class: Gedmo\Sortable\SortableListener
        calls:
            - [setAnnotationReader, ['@annotation_reader']]
        tags:
            - { name: doctrine.event_subscriber, connection: default }
