sonata_media:
    # if you don't use default namespace configuration
    class:
        media: App\Entity\Media
        gallery: App\Entity\Gallery
        gallery_has_media: App\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

        employee:  # the employee context is mandatory
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

        performance:  # the performance context is mandatory
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

        post:  # the post context is mandatory
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
                main:  { width: 600 , height: 400 , quality: 70 }

        history:  # the history context is mandatory
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

        slider:  # the performance slider image context is mandatory
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70}
                slider: { height: 500 , quality: 70}
    cdn:
        server:
            path: "%env(CDN_DOMAIN)%/uploads" # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  "%kernel.project_dir%/public/uploads"
            create:     false

    providers:
        image:
            resizer: sonata.media.resizer.simple
