sonata_media:
    # if you don't use default namespace configuration
    class:
        media: App\Entity\Media
        gallery: App\Entity\Gallery
        gallery_item: App\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

        employee:  # the employee context is mandatory
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

        performance:  # the performance context is mandatory
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

        post:  # the post context is mandatory
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
                main:  { width: 600 , height: 400 , quality: 70 }

        history:  # the history context is mandatory
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

        slider:  # the performance slider image context is mandatory
            providers:
                - sonata.media.provider.image

            formats:
                small: { width: 100 , quality: 70}
                slider: { height: 500 , quality: 70}
    cdn:
        server:
            path: "%env(CDN_DOMAIN)%"
        fallback:
            primary:    sonata.media.cdn.cloudfront
            fallback:   sonata.media.cdn.server
        cloudfront:
            path:       "https://d19uvk3ouw5m5y.cloudfront.net"
            distribution_id: E3CM3AY2JR0BVO
            region: eu-central-1
            version: '2020-05-31' # https://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html
            key: "%env(S3_ACCESS_KEY)%"
            secret: "%env(S3_SECRET_KEY)%"

    filesystem:
        local:
            directory:  "%kernel.project_dir%/public/uploads"
            create:     false
        s3:
            bucket:      "%env(S3_BUCKET_NAME)%"
            accessKey:   "%env(S3_ACCESS_KEY)%"
            secretKey:   "%env(S3_SECRET_KEY)%"
            region:      "%env(S3_REGION)%"
            version:     "latest"

    providers:
        image:
            filesystem: sonata.media.filesystem.s3
            resizer: sonata.media.resizer.simple
            cdn:        sonata.media.cdn.fallback
