twig:
    paths:
        'vendor/sonata-project/admin-bundle/src/Resources/views': SonataAdminBundle
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - 'bundles/SonataAdmin/datepicker.html.twig'
