language: php
php:
  - 7.2

before_script:
    - composer self-update
    - composer install
    - bin/console doctrine:database:import 2020-01-30-theatre-dump.sql --env=test
    - bin/console doctrine:migrations:migrate --no-interaction --env=test

script:
  - phpunit
  - phpunit
