language: php
php:
  - 7.1

before_script:
    - composer self-update
    - composer install
    - php bin/reload
    - app/console cache:clear --env=api

script:
  - phpunit -c app/
  - phpunit -c app/
