language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7

env:
  - SYMFONY_VERSION=2.6.*

before_script:
    - composer self-update
    - composer install
    - php bin/reload

script:
  - phpunit -c app/
  - phpunit -c app/ --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
