language: php
php:
  - 7.4

env:
  global:
    - XDEBUG_MODE=coverage

services:
  - mysql

before_script:
  - composer self-update
  - composer install
  - cp .env.test.travis .env.test.local
  - bin/console doctrine:database:create --env=test
  - mysql -u root chetheatre_test < 2021-01-01-theatre-dump.sql
  - bin/console doctrine:migrations:migrate --no-interaction --env=test
  - bin/phpunit --version

script:
  - XDEBUG_MODE=coverage bin/phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
