services:
    app.command.ticket.generate_set:
        class:  AppBundle\Command\GenerateTicketsCommand
        tags:
            - {name: console.command}
        arguments:
            - @app.ticket.generate_set_handler
            - @app.repository.performance_event
            - @app.repository.ticket
