<?php

namespace AppBundle\Repository;

/**
 * CustomerRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUsernameByApiKey($param)
    {
        return $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.apiKey = :param')
            ->setParameter(':param', $param)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function findUserByFacebookId($param)
    {
        return $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.facebookID = :param')
            ->setParameter(':param', $param)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
