imports:
    - { resource: config_dev.yml }

parameters:
    locale: en

framework:
    translator:      { fallback: "en" }
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

sonata_translation:
    default_locale: en
