gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

_admin:
    resource: routing_admin.yml

_api:
    resource: routing_api.yml

app_swagger_ui_index:
    path: /doc/
    defaults: { _controller: AppBundle:Default:swaggerUi }
    methods: [GET]

app_swagger_ui_static_resource:
    path: /doc/{resource}
    defaults: { _controller: AppBundle:Default:swaggerUiStaticResource }
    methods: [GET]

login:
  pattern:  /login
  defaults: { _controller: AppBundle:Default:login }
