admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: %admin_dashboard_base_url%/

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: %admin_dashboard_base_url%/

login:
  pattern:  /login
  defaults: { _controller: AppBundle:Default:login }

login_check:
  pattern: %admin_dashboard_base_url%/login_check

logout:
  pattern: %admin_dashboard_base_url%/logout

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: sonata_admin_dashboard
        permanent: true
