employees:
    type: rest
    resource: AppBundle\Controller\EmployeesController

performances:
    type: rest
    resource: AppBundle\Controller\PerformancesController

performance-events:
    type: rest
    resource: AppBundle\Controller\PerformanceEventsController

posts:
    type: rest
    resource: AppBundle\Controller\PostsController

tags:
    type: rest
    resource: AppBundle\Controller\TagsController

history:
    type: rest
    resource: AppBundle\Controller\HistoryController

_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.xml"
    prefix: /monitor/health

swagger_ui_index:
    path: /
    defaults: { _controller: AppBundle:SwaggerUi:index }
    methods: [GET]

swagger_ui_doc_file:
    path: /theatre.json
    defaults: { _controller: AppBundle:SwaggerUi:docFile }
    methods: [GET]
