gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

_admin:
    resource: routing_admin.yml

_api:
    resource: routing_api.yml

swagger_ui_index:
    path: /doc/
    defaults: { _controller: AppBundle:SwaggerUi:index }
    methods: [GET]

login:
  pattern:  /login
  defaults: { _controller: AppBundle:Default:login }


