employees:
    type: rest
    resource: AppBundle\Controller\EmployeesController

orders:
    type: rest
    resource: AppBundle\Controller\OrdersController

performances:
    type: rest
    resource: AppBundle\Controller\PerformancesController

performance-events:
    type: rest
    resource: AppBundle\Controller\PerformanceEventsController

posts:
    type: rest
    resource: AppBundle\Controller\PostsController

tags:
    type: rest
    resource: AppBundle\Controller\TagsController

tickets:
    type: rest
    resource: AppBundle\Controller\TicketsController

history:
    type: rest
    resource: AppBundle\Controller\HistoryController

_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.xml"
    prefix: /monitor/health

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /
