admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: %admin_dashboard_base_url%/

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: %admin_dashboard_base_url%/

logout:
  pattern: %admin_dashboard_base_url%/logout
