#!/usr/bin/env php
<?php

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
//umask(0000);

set_time_limit(0);

require_once __DIR__.'/bootstrap.php.cache';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), getenv('SYMFONY_ENV') ?: 'dev');
$domain = $input->getParameterOption(array('--domain', '-d'));
if (!$domain) {
    $output = new Symfony\Component\Console\Output\ConsoleOutput();
    $formatter = new \Symfony\Component\Console\Helper\FormatterHelper();
    $output->writeln($formatter->formatBlock("You must specify domain name", 'error', true));

    exit(1);
}
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

if ($debug) {
    Debug::enable();
}

$kernel = new AppKernel($env, $debug);
$kernel->setDomain($domain);
$application = new Application($kernel);
$application->run($input);
