services:
  stof_doctrine_extensions.listener.blameable:
    class: '%stof_doctrine_extensions.listener.blameable.class%'
    tags:
      - { name: 'doctrine.event_subscriber', connection: 'default' }
    calls:
      - setAnnotationReader: ['@annotation_reader']
      - setUserValue: ['test-user']
