name: Test and Deploy

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  test:
    name: Test code base
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: ctype, iconv, intl, json
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '5.7' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'chetheatre_test' # Optional, default value is "test". The specified database which will be create
          mysql root password: 'pass' # Required if "mysql user" is empty, default is empty. The root superuser password
      - uses: actions/checkout@v2
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer install --prefer-dist
      - name: Reload
        run: bash bin/reload.sh test
      - name: Run tests
        run: XDEBUG_MODE=coverage bin/phpunit --coverage-clover=coverage.clover
